/* THIS (.ts) FILE IS GENERATED BY TypedSignalR.Client.TypeScript */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import type { IStreamResult, Subject } from '@microsoft/signalr';

export type IAudioHub = {
    /**
    * @param stream Transpiled from System.Threading.Channels.ChannelReader<byte>
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    uploadAudioStream(stream: Subject<number>): Promise<void>;
    /**
    * @returns Transpiled from System.Threading.Tasks.Task<string>
    */
    getHelloWorld(): Promise<string>;
}

